In [1]:
import plotly
import pandas
import numpy
import scipy
import plotly.plotly as py
import plotly.graph_objs as go

# Importando os dados
# RRLS = pandas.read_csv("RRLS.csv")
ILS = pandas.read_csv("ILS.csv")
ILS_S = pandas.read_csv("ILS_S.csv")

MAX_FITNESS = {"abba": 43, "aman-aplan": 40, "four": 42, "order": 42, "ranges": 42, "triples": 42,"words": 40}
FITNESS_LINE = go.Scatter(name="Max Fitness", x=list(MAX_FITNESS.keys()), y=list(MAX_FITNESS.values()), mode='lines', marker=go.Marker(color='rgb(255, 77, 77)'))

In [3]:
# Boxplot comparando 'melhor fitness'
data = [
    # go.Box(name="RRLS", x=RRLS.Nome, y=RRLS.Melhor_fitness),
    go.Box(name="ILS", x=ILS.Nome, y=ILS.Melhor_fitness),
    go.Box(name="ILS_S", x=ILS_S.Nome, y=ILS_S.Melhor_fitness),
    FITNESS_LINE,
]

layout = go.Layout(title="Melhor fitness",
                xaxis=dict(title='Inst√¢ncias'),
                yaxis=dict(title='fitness'),
                boxmode='group')
fig = go.Figure(data=data, layout=layout)

py.iplot(fig)

In [4]:
ILS

,Nome,Depth,i,Melhor_solucao,Melhor_fitness,Numero_de_comparacoes,Tempo_para_encontrar_melhor_solucao,Tempo_total,Timed_out
0,abba,5,1,NaN,0,0,60105,60105,True
1,abba,5,2,NaN,0,0,60807,60807,True
2,abba,5,3,NaN,0,0,60953,60953,True
3,abba,5,4,NaN,0,0,60013,60013,True
4,abba,5,5,NaN,0,0,61224,61224,True
5,abba,5,6,NaN,0,0,60510,60510,True
6,abba,5,7,NaN,0,0,61254,61254,True
7,abba,5,8,NaN,0,0,60883,60883,True
8,abba,5,9,NaN,0,0,61405,61405,True
9,abba,5,10,NaN,0,0,60856,60856,True
10,abba,5,11,NaN,0,0,60091,60091,True
11,abba,5,12,NaN,0,0,60100,60100,True
12,abba,5,13,NaN,0,0,60187,60187,True
13,abba,5,14,NaN,0,0,61345,61345,True
14,abba,5,15,NaN,0,0,60754,60754,True
15,abba,5,16,NaN,0,0,60681,60681,True
16,abba,5,17,NaN,0,0,61194,61194,True
17,abba,5,18,NaN,0,0,60794,60794,True
18,abba,5,19,NaN,0,0,61055,61055,True
19,abba,5,20,NaN,0,0,60617,60617,True
20,abba,5,21,NaN,0,0,60840,60840,True
21,abba,5,22,NaN,0,0,60738,60738,True
22,abba,5,23,NaN,0,0,61179,61179,True
23,abba,5,24,NaN,0,0,60666,60666,True
24,abba,5,25,NaN,0,0,61106,61106,True
25,abba,5,26,NaN,0,0,60932,60932,True
26,abba,5,27,NaN,0,0,61262,61262,True
27,abba,5,28,NaN,0,0,61170,61170,True
28,abba,5,29,NaN,0,0,61289,61289,True
29,abba,5,30,NaN,0,0,60563,60563,True
...,...,...,...,...,...,...,...,...,...
210,words,5,1,x|oo|^k|py$|^r|^t|d$,35,209199,11459,35111,False
211,words,5,2,x|oo|^k|py$|^r|^t|d$,35,209199,11399,34873,False
212,words,5,3,x|oo|^k|py$|^r|^t|d$,35,209199,11539,35247,False
213,words,5,4,x|oo|^k|py$|^r|^t|d$,35,209199,11617,37877,False
214,words,5,5,x|oo|^k|py$|^r|^t|d$,35,209199,13481,46037,False
215,words,5,6,x|oo|^k|py$|^r|^t|d$,35,209199,14192,45903,False
216,words,5,7,x|oo|^k|py$|^r|^t|d$,35,209199,15476,47198,False
217,words,5,8,x|oo|^k|py$|^r|^t|d$,35,209199,13626,44127,False
218,words,5,9,x|oo|^k|py$|^r|^t|d$,35,209199,12485,38569,False
219,words,5,10,x|oo|^k|py$|^r|^t|d$,35,209199,11644,38015,False
220,words,5,11,x|oo|^k|py$|^r|^t|d$,35,209199,12095,37926,False
221,words,5,12,x|oo|^k|py$|^r|^t|d$,35,209199,12680,42004,False
222,words,5,13,x|oo|^k|py$|^r|^t|d$,35,209199,15422,45230,False
223,words,5,14,x|oo|^k|py$|^r|^t|d$,35,209199,18106,55638,False
224,words,5,15,x|oo|^k|py$|^r|^t|d$,35,209199,16226,51847,False
225,words,5,16,x|oo|^k|py$|^r|^t|d$,35,209199,20815,55225,False
226,words,5,17,x|oo|^k|py$|^r|^t|d$,35,209199,15945,46786,False
227,words,5,18,x|oo|^k|^t|^r|v|d|h$,35,276771,27335,60035,True
228,words,5,19,x|oo|^k|py$|^r|^t|d$,35,209199,21033,60018,True
229,words,5,20,x|oo|^k|py$|^r|^t|d$,35,209199,17891,56978,False
230,words,5,21,x|oo|^k|py$|^r|^t|d$,35,209199,19477,60042,True
231,words,5,22,x|oo|^k|py$|^r|^t|d$,35,209199,15969,43530,False
232,words,5,23,x|oo|^k|py$|^r|^t|d$,35,209199,12547,42745,False
233,words,5,24,x|oo|^k|py$|^r|^t|d$,35,209199,14769,39939,False
234,words,5,25,x|oo|^k|py$|^r|^t|d$,35,209199,11841,37735,False
235,words,5,26,x|oo|^k|py$|^r|^t|d$,35,209199,14453,41286,False
236,words,5,27,x|oo|^k|py$|^r|^t|d$,35,209199,15040,42330,False
237,words,5,28,x|oo|^k|py$|^r|^t|d$,35,209199,12367,37460,False
238,words,5,29,x|oo|^k|py$|^r|^t|d$,35,209199,13605,43309,False
239,words,5,30,x|oo|^k|py$|^r|^t|d$,35,209199,13446,42645,False